/**
 * REST API for Flexicore filtered by your access rights
 * Flexicore REST API
 *
 * OpenAPI spec version: V3.2.0
 * Contact: avishay@flexi-core.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Baseclass } from '@flexicore/flexicore-client';
import { ScenarioTriggerType } from './scenarioTriggerType';

export interface ScenarioTrigger extends Baseclass { 
    lastEventId?: string;
    lastActivated?: Date;
    validFrom?: Date;
    cooldownIntervalMs?: number;
    activeTill?: Date;
    activeMs?: number;
    logFileResource?: any;
    evaluatingJSCode?: any;
    scenarioTriggerType?: ScenarioTriggerType;
    validTill?: Date;
    javaType?: string;
}